baseURL = "https://master--pest-exterminator-toad-48333.netlify.com/"
languageCode = "ko"
title = "쿨에스엠에스 API References"
theme = "docuapi"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "ko"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "bash"
name = "CURL" 
[[params.language_tabs]]
key = "javascript"
name = "Javascript"
[[params.language_tabs]]
key = "python"
name = "Python"
[[params.language_tabs]]
key = "php"
name = "PHP"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "DocuAPI Example Site"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Sign Up for a Developer Key</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


[languages.ko]
languageName = "한국어"
weight = 1
title = "쿨에스엠에스 API References"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Registrer deg for ein utviklarnøkkel</a>",
"Dokumentasjonen er driven av [DocuAPI](https://github.com/bep/docuapi)",
"API Documents by [쿨에스엠에스](https://www.coolsms.co.kr)"
]

[languages.ko.blackfriday]
# Norwegian uses angled quotes
angledQuotes = true
hrefTargetBlank = true
