baseUrl = "/"
publishDir = "../public"
title = "COOLSMS API References"
theme = "dimension"
languageCode = "ko"
defaultContentLanguage = "ko"
enableRobotsTXT = true
disableRSS = true
hasCJKLanguage = true

[params]
  title = "COOLSMS API References"
  description = '<!--[-->쿨에스엠에스의 모든 API Reference 를 모았습니다.<!--]--><br />
                <!--[-->서비스 사이트는 <a href="https://www.coolsms.co.kr/">여기</a>를 눌러 이동하세요.<!--]-->'
  #logo = "fa-diamond"
  logoimage = "images/nurigo86x86.png"
  copyright = "NURIGO Inc."

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "facebook.com/nurigoinc"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "COOLSMS API References"
description = '<!--[-->Documents for integration of text messages.<!--]--><br />
                <!--[-->서비스 사이트는 <a href="https://www.coolsms.co.kr/">여기</a>를 눌러 이동하세요.<!--]-->'

[languages.ko]
languageName = "한국어"
weight = 2
title = "COOLSMS API References"
description = '<!--[-->쿨에스엠에스의 모든 API Reference 를 모았습니다.<!--]--><br />
                <!--[-->서비스 사이트는 <a href="https://www.coolsms.co.kr/">여기</a>를 눌러 이동하세요.<!--]-->'
