baseURL = "/"
languageCode = "ko"
DefaultContentLanguage = "ko"

title = "Docdock"
theme = "hugo-theme-docdock"
#themesdir = "../.."

[params]
editURL = "https://github.com/coolsms/coolsms-api-docs/edit/master/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<hr>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "github"
url = "https://github.com/coolsms"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> API Reference"
identifier = "rest-api"
url = "https://docs.coolsms.co.kr/rest-api/"
weight = 20
